### ISSUE TITLE
Bug with Conch

### ISSUE THREAD

**Issue by juancarlospaco** [AndreiRegiani/INim#11]
- Bug with [Xon.sh Shell, the Python-ish Bash shell](http://xon.sh), Im using latest version of both, Linux.

![temporales](https://user-images.githubusercontent.com/1189414/39401769-087c3ff6-4b24-11e8-8458-07832fb59e0c.png)

:cat:

**Comment by AndreiRegiani** [comment]
I couldn't reproduce. I tried with the similar environment: `xonsh/0.6.2`, `Konsole/17.04.3`, `INim 0.2.1`, `Nim 0.18.1`, `Ubuntu 17.10`. Any ideas? Does it work with any other shell?

**Comment by juancarlospaco** [comment]
NVM.
