### ISSUE TITLE
How to Install INim?

### ISSUE THREAD

**Issue by A-p-p-u** [AndreiRegiani/INim#13]
I have

> nim -v
> Nim Compiler Version 0.18.0 [Linux: amd64]

I was trying to install inim

> nimble install inim --verbose
> Reading official package list
> Downloading https://github.com/AndreiRegiani/INim using git
> Cloning latest tagged version: 0.2.5
> Setting Nim stdlib prefix to /home/appu/Nim
> Setting Nim stdlib path to /home/appu/Nim/lib
> Verifying dependencies for inim@0.2.5
> Error: Couldn't find Nim version.
> 

I tried

> which nim
> /home/appu/.nimble/bin/nim

and

> whereis nim
> nim: /usr/lib/nim /etc/nim.cfg /usr/share/nim /home/appu/bin/nim /home/appu/.nimble/bin/nim /home/appu/Nim/bin/nim

What should I do?

**Comment by AndreiRegiani** [comment]
Can you install other Nimble packages?

It seems the problem is with your Nim installation, I recommend using `choosenim`: https://nim-lang.org/install.html

To install should be `nimble install inim`, then `inim` to open.

**Comment by A-p-p-u** [comment]
I am sorry, so this is a bug in choosenim after all! Nimble attempts to read ~/.config/nimble/nimble.ini. Choosenim has not created such a directory. I should have reported a bug there.
