### ISSUE TITLE
import strformat and fmt"foo" doesn't work: Error: undeclared identifier

### ISSUE THREAD

**Issue by timotheecour** [AndreiRegiani/INim#17]
```
>>> import strformat
>>> fmt"asdf"
inim_1530775518.nim(2, 6) Error: undeclared identifier: 'fmtRes194003'
>>> let a=fmt"asdf"
Error: undeclared identifier: 'fmtRes194003'
```

nim c -r test1.nim
works
with:
```
cat test1.nim
import strformat

let a=fmt"asdf"
echo a
```

**Comment by timotheecour** [comment]
NOTE: same bug even after https://github.com/AndreiRegiani/INim/pull/24/commits/32971373c2be7a6d68081619e25e696ec8b9aa0f
looks like the logic from https://github.com/AndreiRegiani/INim/commit/3b7c62a1161c4f52d66e15bf41a0323f5b273051 is too frail for that case.
workaround: echo `fmt"asdf"`

NOTE: maybe using the compiler as a library `compiler/nimeval` and checking whether we get an Expr or Statement would work better?

**Comment by AndreiRegiani** [comment]
Fixed for all cases.

```bash
nim> import strformat
nim> fmt"asdf"
asdf  : string
nim> echo fmt"asdf"
asdf
```

>compiler/nimeval

I will use this to check expressions while indented, if there's an error just ignore it and you can continue typing inside the same indent without losing previous commands.
