### ISSUE TITLE
'which nim' error on Windows

### ISSUE THREAD

**Issue by matkuki** [AndreiRegiani/INim#2]
Hi,

Installation via **nimble** goes smoothly, but when running on Windows 10, I get:
```
INim 0.1.0
Nim Compiler Version 0.18.0 [Windows: i386]
Error: unhandled exception: The system cannot find the file specified.

Additional info: Requested command not found: 'which nim'. OS error: [OSError]
```
Shouldn't it be 'where nim' on Windows?

**Comment by AndreiRegiani** [comment]
Fixed in master branch. Run again: `nimble install inim` 
Thanks for reporting, I forgot about Windows users.

**Comment by matkuki** [comment]
Yes, it works now! Thanks
