### ISSUE TITLE
Request for executable (at least for Windows)

### ISSUE THREAD

**Issue by Tallefer** [AndreiRegiani/INim#25]
CAN I HAZ A BINARY PLZ
,,,^. .^,,,
Reason — to provide a better "playground" experience for Nim. INim is closer to hardware than online in-browser interpreters and therefore has the potential to be much faster. 
But without an easily accessible binary executable people with urge to immediately try Nim are losing this kind of opportunity. Self-contained portable package would be awesome to have. :)
Thank you!

**Comment by Yardanico** [comment]
@Tallefer well, that's actually possible (for Windows):
Use Enigma VirtualBox (it's freeware)
pack GCC, Nim (devel) and INim in one executable
???
PROFIT!

But executable size will be big and people will say "nah, I'm not downloading a executable this big".
Also it should be clear for people from the start that Nim IS NOT INTERPRETED.

**Comment by Tallefer** [comment]
Well, it's an option, sure, but not very "native", don't you agree? :) 
By the way, is TCC an option at all? Could be a very noticeable difference in size. Nim docs even say about using TCC as a (kinda) quasy-interpreter, because of its compiling speed.
And I don't think people are perceiving Nim as interpreted language, at least I never saw one myself. :) But I had conversations with people that are hyped by just discovering Nim and are asking many questions, for which I had previously only one answer (besides, obviously, compiling everything the "proper" way) — online interpreters. 
Could you please at least provide more instructions in readme on how to get a working INim quickly? :)

**Comment by Yardanico** [comment]
@Tallefer just install choosenim, add  $USER/.nimble/bin to PATH, run `nimble install inim` and you're done.

**Comment by Tallefer** [comment]
@Yardanico Choosenim is a nice option, sure. But messing with PATH to achieve (local) portability and taking even further steps is exactly what I am trying to avoid. :)
Portable self-contained package is what I need.

**Comment by 0atman** [comment]
Hi friends! @Tallefer I think you'll always need a nim compiler, inim compiles stuff on the fly using it, so what you want, a completely independent executable that ALSO includes nim is not possible without a rewrite.

Just as you can't have `ipython` without `python`, you can't have `inim` without `nim`, sorry!

**Comment by 0atman** [comment]
@Yardanico's solution of `nimble install inim` is the correct one. You don't need to mess with paths if you don't want to, just `mv` the compiled `inim` binary to somewhere already on your path.
