### ISSUE TITLE
lots of inim_xxxx.exe files created on Windows!

### ISSUE THREAD

**Issue by matkuki** [AndreiRegiani/INim#3]
On Windows the **inim_xxxx.exe** file and the **nimcache** directory do not get cleaned up after exiting the interpreter. Also, if you quit break from the interpreter with **Ctrl+C**, the **inim_xxxx.nim** file does not get deleted.
Example: If I run inim.exe 5 times, then 5 **inim_xxxx.exe** files get created in the current working directory.

**Comment by AndreiRegiani** [comment]
@matkuki Should be fixed on latest release `0.2.0`, update INim `nimble install inim`.
https://github.com/AndreiRegiani/INim/releases/tag/0.2.0

Let me know if worked well on Windows, now should be using its temp folder.

**Comment by matkuki** [comment]
Hey @AndreiRegiani ,
Yes, the files are now created in the users AppData/Local/Temp directory.
Very good, thanks!
