### ISSUE TITLE
Windows IOError

### ISSUE THREAD

**Issue by matkuki** [AndreiRegiani/INim#40]
Hi,

Installed the latest INim with today's devel version of Nim x64 on Windows 10 x64 and get the following error when executing `inim.exe`:
```
Error: unhandled exception: Unknown IO Error [IOError]
```

Any ideas?

**Comment by Yardanico** [comment]
Are you running `inim` inside of VSCode?

**Comment by matkuki** [comment]
@Yardanico No, standard windows console.

**Comment by AndreiRegiani** [comment]
Update to v0.4.1: `nimble install inim`

https://github.com/AndreiRegiani/INim/releases/tag/0.4.1

Let me know if this works for you. Since I don't usually test on Windows next time I will wait a bit longer before a public release, thanks for the quick feedback.

**Comment by Yardanico** [comment]
@AndreiRegiani btw, you can use colors from `terminal` stdlib package (they're cross-platform and will work  on windows, linux, macos, etc)

**Comment by AndreiRegiani** [comment]
I'm using `import terminal` for INim itself, but for the temp user code it
increases the compilation time for each expression (1 second?) affecting
the smooth usability, for POSIX I'm echoing the raw color codes.

**Comment by matkuki** [comment]
@AndreiRegiani It works! Thanks
