### ISSUE TITLE
Can't install inim.

### ISSUE THREAD

**Issue by Alihusejn** [AndreiRegiani/INim#43]
C:\Users\User>nimble install inim
Downloading https://github.com/AndreiRegiani/INim using git
  Verifying dependencies for inim@0.4.1
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.16
 Installing inim@0.4.1
   Building inim/inim.exe using c backend
    Prompt: Build failed for 'inim@0.4.1', would you like to try installing 'inim@#head' (latest unstable)? [y/N]
    Answer: y
Downloading https://github.com/AndreiRegiani/INim using git
  Verifying dependencies for inim@#head
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.16
 Installing inim@#head
   Building inim/inim.exe using c backend
       Tip: 13 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: inim
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "C:\Users\User\Downloads\nim-0.19.0\bin\nim.exe" c --noBabelPath -d:release --path:"C:\Users\User\.nimble\pkgs\cligen-0.9.16"  -o:"C:\Users\User\AppData\Local\Temp\nimble_3652\githubcom_AndreiRegianiINim_#head\inim.exe" "C:\Users\User\AppData\Local\Temp\nimble_3652\githubcom_AndreiRegianiINim_#head\src\inim.nim"
        ... Output: Hint: used config file 'C:\Users\User\Downloads\nim-0.19.0\config\nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: inim [Processing]
        ... Hint: os [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: times [Processing]
        ... Hint: options [Processing]
        ... Hint: typetraits [Processing]
        ... Hint: strformat [Processing]
        ... Hint: macros [Processing]
        ... Hint: winlean [Processing]
        ... Hint: dynlib [Processing]
        ... Hint: ospaths [Processing]
        ... Hint: osproc [Processing]
        ... Hint: strtabs [Processing]
        ... Hint: hashes [Processing]
        ... Hint: streams [Processing]
        ... Hint: cpuinfo [Processing]
        ... Hint: rdstdin [Processing]
        ... Hint: terminal [Processing]
        ... Hint: colors [Processing]
        ... Hint: tables [Processing]
        ... inim.nim(79, 16) Error: type mismatch: got <nil> but expected 'string'

**Comment by Yardanico** [comment]
https://github.com/AndreiRegiani/INim/issues/42

**Comment by nixfreak** [comment]
I couldn't get this to work just installing inim either. 

here are the steps I did to install inim 

1. nimble install cligen 
2. nimble install inim 

Downloading https://github.com/c-blake/cligen.git using git
  Verifying dependencies for cligen@0.9.38
 Installing cligen@0.9.38
   Success: cligen installed successfully.
Tue Oct 01: nim | nimble install inim
Downloading https://github.com/AndreiRegiani/INim using git
  Verifying dependencies for inim@0.4.1
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.38
 Installing inim@0.4.1
   Building inim/inim using c backend
    Prompt: Build failed for 'inim@0.4.1', would you like to try installing 'inim@#head' (latest unstable)? [y/N]
    Answer: y
Downloading https://github.com/AndreiRegiani/INim using git
  Verifying dependencies for inim@#head
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.38
 Installing inim@#head
   Building inim/inim using c backend
   Warning: Symlink already exists in /Users/aaronm/.nimble/bin/inim. Replacing.
   Success: inim installed successfully.
