### ISSUE TITLE
print values without using "echo"

### ISSUE THREAD

**Issue by jabbalaci** [AndreiRegiani/INim#49]
Coming from Python, I really like that you can do this:

```python
>>> a = 7
>>> a
7
>>> 1+1
2
```

That is, when you create a variable, you can print its value without using the `print()` function. The same is true for expressions.

INim works like this at the moment:

```nim
nim> var a = 7
nim> a
Error: expression 'a' is of type 'int' and has to be discarded; start of expression here: inim_1539330313.nim(1, 0)
nim> 1+1
Error: expression '2' is of type 'int literal(2)' and has to be discarded; start of expression here: inim_1539330313.nim(1, 0)
nim>
```

It would be great if we could mimic the Python REPL. Maybe it could be done like this: try to execute the line as it is. If there is an error, rewrite the line by adding "echo" to the beginning of the line and re-execute the line. The second time output everything.

Or, a less appealing solution could be to define an alias function called "e" for instance that points on "echo". Thus we could print easier:

```nim
>>> var a = 7
>>> e a    # short for `echo a`
7
>>>

**Comment by bevo009** [comment]
The `nim secret` REPL does just that, like the python REPL.  So you can go:
```
>>>11 / 3
3.66666666666666667
>>>11 div 3
3
>>> 11 mod 3
2
```
etc etc... just type `nim secret` at the prompt. It's not as pretty as iNim and doesn't support Ctrl-L to clear the screen, but for simple Nim maths calculation and printing variables, it's fine.
A VS Code tip, if you temporarily rename the file extension to .py in the sidebar, you can use shift-enter to send selected lines to  iNim (via the Python extension)...just Ctrl-D out and inim back in, and you can shift-enter send-to repl from then on...useful until the Nim plugin gets that feature. It also works for nim secret, coconut etc.

**Comment by Tangdongle** [comment]
Pull Request up; https://github.com/AndreiRegiani/INim/pull/53

**Comment by 0atman** [comment]
#53 Is MERGED!
