### ISSUE TITLE
Allow symbol definition on inim startup ie -d:ssl

### ISSUE THREAD

**Issue by ghost** [AndreiRegiani/INim#50]
I'm currently writing some code that needs SSL support, done by compiling with the `-d:ssl` switch. It doesn't seem inim has support for passing custom switches to the compiler though, so my code doesn't work with inim.

It'd be great to allow arbitrary parameters to be passed to the compiler.

**Comment by Tangdongle** [comment]
Pull Request up https://github.com/AndreiRegiani/INim/pull/51

**Comment by 0atman** [comment]
Pull request MERGED!
