### ISSUE TITLE
error on build, nil is used instead of empty string

### ISSUE THREAD

**Issue by JotaPe** [AndreiRegiani/INim#54]
I have find some problems trying to compile the latest tagged version,  0.4.1, I have found that it was a problem with nil being returned when causing a type mismatch.

**Comment by Tangdongle** [comment]
I think this can be closed with the addition of the latest 4.2 tag.
Error was fixed with this line: https://github.com/AndreiRegiani/INim/commit/22d6c4912e12871c2f51a3cf089b559d2051156c#diff-480409da1921d4ce086b3b4d84c83cb7R79
